language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
script: mvn compile test
install: true
notifications:
  email:
    recipients:
      - "benjaminesims@gmail.com"
    on_success: change
    on_failure: always